esphome:
  name: light-kitchen-cupboards
  platform: ESP8266
  board: d1_mini

  # Sets the light to 50% on boot
  on_boot:
    priority: 700
    then:
      - light.turn_on:
          id: led_lights
          brightness: 50%
      - light.turn_off: led_lights

substitutions:
  # Enter the name of the Room here - Capitals and Spaces are ok. However...
  # capitals and spaces will get converted for entity names. E.G. the Light will be called "light.kitchen_cupboards"
  name: Kitchen Cupboards

  # Timer duration (Minutes). E.G.: "60" 1 hour, "0.1" 6 Seconds
  off_time: "10"

# Replace your Wifi details
wifi:
  ssid: !secret ssid
  password: !secret wifi_password

# ====== Nothing needs changing below this line ======

logger:
  logs:
    light: none
    binary_sensor: none
    switch: none
api:
ota:

switch:
  - platform: template
    id: day_night_mode
    name: ${name} Day / Night
    optimistic: true

binary_sensor:
  - platform: template
    id: timer

  - platform: gpio
    id: motion_sensor
    name: ${name} Motion
    pin: D6
    device_class: motion
    on_press:
      then:
        - if:
            condition:
              and:
                - light.is_off: led_lights
                - switch.is_on: day_night_mode
            then:
              - light.turn_on:
                  id: led_lights
                  brightness: !lambda |-
                    return id(led_lights).current_values.get_brightness();
              - lambda: !lambda |-
                  id(timer).publish_state(true);
            else:
              - script.stop: timeout
    on_release:
      then:
        - if:
            condition:
              - binary_sensor.is_on: timer
            then:
              - script.execute: timeout

script:
  - id: timeout
    mode: restart
    then:
      - if:
          condition:
            - binary_sensor.is_on: timer
          then:
            - delay: ${off_time} minutes
            - light.turn_off: led_lights
            - lambda: !lambda |-
                id(timer).publish_state(false);

light:
  - platform: monochromatic
    id: led_lights
    name: ${name}
    output: output_pwm
    default_transition_length: 1s
output:
  - platform: esp8266_pwm
    frequency: 4000
    id: output_pwm
    pin: D8
