esphome:
  name: light-kitchen-cupboards
  platform: ESP8266
  board: d1_mini
  
  # Sets the light to 20% on boot
  on_boot:
    priority: 700
    then:
      - light.turn_on:
          id: leds
          brightness: 20%
      - light.turn_off: leds

substitutions:
  # Enter the name of the Room here - Capitals and Spaces are ok. However...
  # capitals and spaces will get converted for entity names. E.G. the Light will be called "light.kitchen_cupboards"
  name: Kitchen Cupboards
  
  # Timer duration (Minutes). E.G.: "60" 1 hour, "0.1" 6 Seconds
  off_time: "0.1" 

# Replace your Wifi details
wifi:
  ssid: !secret ssid
  password: !secret wifi_password

# ====== Nothing needs changing below this line ======

logger:
  logs:
    light: none
    binary_sensor: none
    switch: none
api:
ota:

switch:
  - platform: template
    id: day_night_mode
    name: ${name} Day / Night
    optimistic: true

binary_sensor:
  - platform: template
    id: timer

- platform: gpio
    id: motion_sensor
    name: ${name} Motion
    pin: D6
    device_class: motion
    
    on_press:
      then:
        - if:
            condition:
              - light.is_off: leds
              - switch.is_on: day_night_mode
            then:
              - light.turn_on:
                  id: leds
                  brightness: !lambda |-
                    return id(leds).current_values.get_brightness();
              - lambda: !lambda |-
                  id(timer).publish_state(true);
            else:
              - script.stop: timeout
    on_release:
      then:
        - if:
            condition:
              - binary_sensor.is_on: timer
            then:
              - script.execute: timeout

script:
  - id: timeout
    mode: restart
    then:
      - if:
          condition:
            - binary_sensor.is_on: timer
          then:
            - delay: ${off_time} minutes
            - light.turn_off: leds
            - lambda: !lambda |-
                id(timer).publish_state(false);

light:
  - platform: monochromatic
    id: leds
    name: ${name}
    output: string
    default_transition_length: 2s

output:
  - platform: esp8266_pwm
    frequency: 3000
    id: string
    pin: D8
